-- Missing Columns Migration Script
-- Add missing columns to existing tables based on entity classes


-- 2. Create categories table (completely missing)
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- 3. Update interests table to add missing columns
ALTER TABLE interests 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- Add foreign key constraint for interests.category_id
ALTER TABLE interests 
ADD CONSTRAINT IF NOT EXISTS fk_interests_category 
    FOREIGN KEY (category_id) REFERENCES categories(id);

-- 4. Update user_interests table to add missing columns
ALTER TABLE user_interests 
ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ADD COLUMN IF NOT EXISTS proficiency_level INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- Drop the existing primary key and recreate it properly
ALTER TABLE user_interests DROP CONSTRAINT IF EXISTS user_interests_pkey;

-- 5. Update duties table to add missing columns
ALTER TABLE duties 
ADD COLUMN IF NOT EXISTS category_id BIGINT,
ADD COLUMN IF NOT EXISTS target_life_stage VARCHAR(50),
ADD COLUMN IF NOT EXISTS min_age INTEGER,
ADD COLUMN IF NOT EXISTS max_age INTEGER,
ADD COLUMN IF NOT EXISTS estimated_cost DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS time_to_complete VARCHAR(255),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- Add foreign key constraint for duties.category_id
ALTER TABLE duties 
ADD CONSTRAINT IF NOT EXISTS fk_duties_category 
    FOREIGN KEY (category_id) REFERENCES categories(id);

-- Update priority column to use VARCHAR for enum
ALTER TABLE duties ALTER COLUMN priority TYPE VARCHAR(50);

-- 6. Create duty_interests junction table (missing)
CREATE TABLE IF NOT EXISTS duty_interests (
    duty_id BIGINT NOT NULL,
    interest_id BIGINT NOT NULL,
    PRIMARY KEY (duty_id, interest_id),
    CONSTRAINT fk_duty_interests_duty 
        FOREIGN KEY (duty_id) REFERENCES duties(id) ON DELETE CASCADE,
    CONSTRAINT fk_duty_interests_interest 
        FOREIGN KEY (interest_id) REFERENCES interests(id) ON DELETE CASCADE
);

-- 7. Update user_duty_progress table to add missing columns
ALTER TABLE user_duty_progress 
ADD COLUMN IF NOT EXISTS duties_id BIGINT,
ADD COLUMN IF NOT EXISTS started_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS personal_notes TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Add foreign key for duties_id (seems to be a different reference than duty_id)
ALTER TABLE user_duty_progress 
ADD CONSTRAINT IF NOT EXISTS fk_udp_duties 
    FOREIGN KEY (duties_id) REFERENCES duties(id) ON DELETE CASCADE;

-- 8. Create goals table (completely missing)
CREATE TABLE IF NOT EXISTS goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category_id BIGINT,
    target_life_stage VARCHAR(50),
    timeframe VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_goals_category 
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- 9. Create goal_duties junction table (missing)
CREATE TABLE IF NOT EXISTS goal_duties (
    goal_id BIGINT NOT NULL,
    duty_id BIGINT NOT NULL,
    PRIMARY KEY (goal_id, duty_id),
    CONSTRAINT fk_goal_duties_goal 
        FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    CONSTRAINT fk_goal_duties_duty 
        FOREIGN KEY (duty_id) REFERENCES duties(id) ON DELETE CASCADE
);

-- 10. Create user_goals table (completely missing)
CREATE TABLE IF NOT EXISTS user_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    target_date TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    personal_notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_user_goals_user 
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_goals_goal 
        FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);

-- Create email verification tokens table
CREATE TABLE email_verification_tokens (
    id BIGSERIAL PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);
CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens(expires_at);
-- Create necessary indexes for performance
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name);
CREATE INDEX IF NOT EXISTS idx_interests_category_id ON interests(category_id);
CREATE INDEX IF NOT EXISTS idx_user_interests_proficiency ON user_interests(proficiency_level);
CREATE INDEX IF NOT EXISTS idx_duties_category_id ON duties(category_id);
CREATE INDEX IF NOT EXISTS idx_duties_life_stage ON duties(target_life_stage);
CREATE INDEX IF NOT EXISTS idx_duties_age_range ON duties(min_age, max_age);
CREATE INDEX IF NOT EXISTS idx_duty_interests_duty ON duty_interests(duty_id);
CREATE INDEX IF NOT EXISTS idx_duty_interests_interest ON duty_interests(interest_id);
CREATE INDEX IF NOT EXISTS idx_goals_category_id ON goals(category_id);
CREATE INDEX IF NOT EXISTS idx_goals_life_stage ON goals(target_life_stage);
CREATE INDEX IF NOT EXISTS idx_goal_duties_goal ON goal_duties(goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_duties_duty ON goal_duties(duty_id);
CREATE INDEX IF NOT EXISTS idx_user_goals_user ON user_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_user_goals_goal ON user_goals(goal_id);
CREATE INDEX IF NOT EXISTS idx_user_goals_status ON user_goals(status);